apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: demo-backend
        image: demo-backend:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 5200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: demo-backend
data:
  BACKEND_PROTOCOL: "http"
  BACKEND_HOST: "localhost"
  BACKEND_PORT: "5200"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  labels:
    service: demo-backend
spec:
  type: LoadBalancer
  selector:
    app: demo-backend
  ports:
  - name: "bind-backend"
    protocol: "TCP"
    port: 5200
    targetPort: 5200
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-backend-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
